### ISSUE TITLE
Error Handling?

### ISSUE THREAD

**Issue by segg21** [ThreeLetters/SuperSQL#9]
If no error handling or proper exceptions, how will I know if my database connection failed or not, besides sending a query testing if it failed?

**Comment by Andrews54757** [comment]
@LegitSoulja What are you talking about? If there is an error, then `new SuperSQL()` will fail and give an error. You can use a try catch statement to catch that.

**Comment by segg21** [comment]
@Andrews54757

Reason why I asked is because in docs/examples there was no checks made. You just connected and sent a query.

I asked because I didn’t see no custom exceptions, or your own try/catches in code and I never used PDO before.

Only reason why I am using SuperSQL instead of mines is because I am making a project for others and not all support mysqli.

But thanks for letting me know. I wanted to make sure before I started using it.
